# mapping (sdf_map/)
frame_id: map
#resolution: 0.05
use_occ_esdf: true


# local_update_range (meter)
min_ray_length: 0.5
max_ray_length: 10.0
local_update_range_x: 10.0
local_update_range_y: 10.0

# inflations (meter)
obstacles_inflation: 0.5
local_bound_inflate: 0.0

# occupancy generation
p_hit: 0.52
p_miss: 0.15
p_min: 0.10
p_max: 0.75
p_occ: 0.70

# local map margin for cell/index
local_map_margin: 0 

# test
show_occ_time: false
show_esdf_time: false



# #footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
# #footprint_inflation: 0.01
# robot_radius: 0.3
# inflation_radius: 0.3
# cost_scaling_factor: 3.0
# map_type: costmap
# #transform_tolerance: 1
# observation_sources: scan
# #scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true} #, sensor_frame: laser_link}
# scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
# #static_laser: {clearing: true, data_type: LaserScan, expected_update_rate: 0.0, marking: true, max_obstacle_height: 0.25, min_obstacle_height: -0.1, sensor_frame: static_laser_link, topic: static_laser}