# timed astar parameters (timed_astar/)
allocate_num: 1000
goal_tolerance: 0.2

robot_radius: 0.3
obstacle_radius: 0.5
inflation_radius: 0.3

max_vel: 2.0
avg_vel: 1.0
min_vel: 0.5
max_rot_vel: 0.52

time_horizon: 5.0
time_resolution: 0.2
resolution: 0.1

num_sample_edge: 10