# timed astar parameters (timed_astar/)
allocate_num: 10000
goal_tolerance: 0.2

sensor_range: 3.0
prediction_forward_time: 0.5
robot_radius: 0.3
obstacle_radius: 0.3
inflation_radius: 0.1

max_vel: 1.5
avg_vel: 1.0
min_vel: 0.5
max_rot_vel: 0.52

time_horizon: 5.0
time_resolution: 0.2
resolution: 0.1

num_sample_edge: 10